spring:
  application:
    name: text-to-speech-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/apps?currentSchema=app-tts
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
    
    
  security:
    cors:
      allowed-origins: "http://localhost:5173"
    csrf:
      enabled: false
 

logging:
  level:
    root: INFO
    com.devcell.tts: DEBUG

server:
  port: 9000


python:
  tts:
    service:
      url: http://localhost:8000
